# Generated by Django 5.0.6 on 2024-07-05 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician_directory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='muisian',
            new_name='muisician',
        ),
    ]
